### ISSUE TITLE
[Rep Tester] Add config file to config mozilla-central and devtools paths

### ISSUE THREAD

**Issue by evanxd** [janodvarko/prototypes#1]
Add config file to config mozilla-central and devtools paths.

**Comment by janodvarko** [comment]
@evanxd: do you see any error messages when using the tool as is?

Honza

**Comment by evanxd** [comment]
Hi @janodvarko ,

I can run Rep Tests after I config the `webpack.config.js`[1](https://github.com/janodvarko/prototypes/blob/master/reps/webpack.config.js) file. I changed these two configs[2](https://github.com/janodvarko/prototypes/blob/master/reps/webpack.config.js#L24), [3](https://github.com/janodvarko/prototypes/blob/master/reps/webpack.config.js#L41) to fit my computer environment.

So looks like people might need to config the paths for using Rep Tester. I wrote a patch[4](https://github.com/janodvarko/prototypes/pull/2) to add a new config file to help people config easier. Please take a look. If it looks good, let's update the document[5](https://github.com/janodvarko/prototypes/blob/master/reps/README.md).

And one more thing, how do you think if we move Rep Tester from prototypes repo[6](https://github.com/janodvarko/prototypes) to a individual repo and publish on npm website? It will be good for it's maintenance and usage.

Evan
